### ISSUE TITLE
STABS: Anonymous union importing issues

### ISSUE THREAD

**Issue by VelocityRa** [chaoticgd/ghidra-emotionengine-reloaded#16]
Game: https://hiddenpalace.org/Sly_Cooper_and_the_Thievius_Raccoonus_(May_19,_2002_prototype)

Lots of imported types contain this invalid type `*__null__-1_-1`:

As an example, take the `VECTOR` class.
![image](https://user-images.githubusercontent.com/6632271/219034162-e9412e8c-3b42-4cb1-b199-4eee4dc83dd6.png)

The struct as emitted with the C exporter is:
```cpp
struct VECTOR { // 0x10
	/* 0x0 */ union { // 0x4
		/* 0x0 */ AS3 as;
		/* 0x0 */ float x;
	};
	/* 0x4 */ float y;
	/* 0x8 */ float z;
	/* 0xc */ float gUnused;
};
```

---

Not sure if significant, but on import the following errors are printed:
```
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: ASO
STABS> Type lookup failed: rtx_def
```

**Comment by chaoticgd** [comment]
This is fixed by #18.
