### ISSUE TITLE
Seeing which bitfield is being used 

### ISSUE THREAD

**Issue by theclub654** [chaoticgd/ghidra-emotionengine-reloaded#56]
Instead of just having the raw offset of the bit field thats being referenced could we see which bitfield is being manipulated or used 
like in the pic you see how its palo->0x2d8 instead of it being that can the bitfield name thats being used be referenced 

![Screenshot 2024-02-08 191049](https://github.com/chaoticgd/ghidra-emotionengine-reloaded/assets/61169936/188da9ab-170c-48fb-b109-2459c9bda1cc)

**Comment by chaoticgd** [comment]
That's a problem with Ghidra's decompiler, so I think there's not really anything for me to fix in the plugin.
