### ISSUE TITLE
Typo in CACHE Instruction GXWBIN

### ISSUE THREAD

**Issue by jessep13** [chaoticgd/ghidra-emotionengine-reloaded#72]
There is no CACHE GXWBIN instruction according to the EE Core Instruction Set Manual. I was able to locate this typo under the `cop0.sinc` file under line 63:
```
GXWBIN _ DXIN _
```
This should instead probably read:
```
DXWBIN _ DXIN _
```
But I'm unsure as to whether this "typo" is actually fully intentional or whether there are other places in the code with said typo. I did original discover the typo via version in SP15 which I pictured below an example of the typo in action:
![image](https://github.com/user-attachments/assets/d4b9f50d-a6fc-4f5a-9537-3d1eb503c8b6)
![image](https://github.com/user-attachments/assets/1a2add29-30ce-45e2-9686-94ec66bfa302)
As evidence for why I think GXWBIN should be DXWBIN, I pictured below an excerpt from the manual of the DXWBIN intrstuction. Notice that the scalar at the start is 0x14 which is the same one in my second picture for GXWBIN.
![image](https://github.com/user-attachments/assets/e0258ca3-a5f9-4a51-af55-b9aeb19c035a)

**Comment by chaoticgd** [comment]
Good catch.
