### ISSUE TITLE
weird function jumps, again [Densha de GO! Final (PS2)]

### ISSUE THREAD

**Issue by modusc896d352** [chaoticgd/ghidra-emotionengine-reloaded#75]
i found an PS2 executable file with weird function jumps between them.
![](https://files.catbox.moe/4kwihz.png)
disabling symbol relocation did basicaly nothing here.
also, for whatever reason, address-set variables, like what you see with v0 and v1 registers, are somehow doubled to what GHIDRA can actually reach. i think these things were already compiled from the get-go.

here's the executable file in question.
[slpm60237_elf.7z](https://files.catbox.moe/uvbgkv.7z)

**Comment by modusc896d352** [comment]
actually that was the executable from the PS2 demo, executable from the final PS2 game can load without issue:
![](https://files.catbox.moe/9crsfa.png)

here's another executable file.
[slpm65590_elf.7z](https://files.catbox.moe/1gp90p.7z)

**Comment by chaoticgd** [comment]
I figured it out: https://github.com/chaoticgd/ghidra-emotionengine-reloaded/pull/76

Can you test the latest unstable build and confirm that it fixes it?

**Comment by modusc896d352** [comment]
ok, testing now.

**Comment by modusc896d352** [comment]
tested. no change. function jumps from the demo executable remain the same.
seems like symbol relocation was not affected by this.

**Comment by chaoticgd** [comment]
Did you use [this](https://github.com/chaoticgd/ghidra-emotionengine-reloaded/releases/download/unstable/ghidra_11.1.2_PUBLIC_20240724_ghidra-emotionengine-reloaded.zip) build and re-import the file from scratch?

I could reproduce the issue before, and after the relocation fix it went away. I also observed that relocations were applied even with the relevant checkbox in the importer unchecked for some reason. To know for sure, can you show a screenshot of the Relocation Table (Window->Relocation Table)?

**Comment by modusc896d352** [comment]
late reply. sorry.

> Did you use [this](https://github.com/chaoticgd/ghidra-emotionengine-reloaded/releases/download/unstable/ghidra_11.1.2_PUBLIC_20240724_ghidra-emotionengine-reloaded.zip) build and re-import the file from scratch?

late reply, but yes. i did in fact use this build. but let me check.

> I could reproduce the issue before, and after the relocation fix it went away. I also observed that relocations were applied even with the relevant checkbox in the importer unchecked for some reason. To know for sure, can you show a screenshot of the Relocation Table (Window->Relocation Table)?

will do.

**Comment by modusc896d352** [comment]
**Relocation Table** screenshot is here:
![](https://files.catbox.moe/wm3pjx.png)
**Status** all say **SKIPPED** for every relocation entry present (out of 37627 rows total).

also, i had to do a fresh install of this new build. here's now disassembled exe looks like now:
![](https://files.catbox.moe/ipy2h3.png)
sorry for bothering you.

**Comment by chaoticgd** [comment]
It's completely fine, if it wasn't for this issue I would've missed that relocation bug.
